apiVersion: gslb.snappcloud.io/v1alpha1
kind: Gslb
metadata:
  name: gslb-sample
  namespace: abar-internal
spec:
  serviceName: hello
  backends:
  - name: private-teh-1
    host: 10.21.232.2
    weight: "1"
    probe:
      failureThreshold: 10 #
      httpGet:
        host: http://spcld-health2-be.apps.private.teh-1.snappcloud.io
        path: /
        port: 80 #
        scheme: HTTP #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3    
  - name: private-teh-2
    host: 10.22.232.2
    weight: "1"
    probe:
      failureThreshold: 10 #
      httpGet:
        host: http://spcld-health2-be.apps.private.teh-2.snappcloud.io
        path: /
        port: 80 #
        scheme: HTTP #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3    
  - name: svc-lb-teh-1
    host: 172.21.56.15
    weight: "1"
    probe:
      failureThreshold: 10 #
      httpGet:
        host: http://172.21.56.15
        path: /
        port: 80 #
        scheme: HTTP #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3    
  - name: svc-lb-teh-2
    host: 172.16.56.5
    weight: "1"
    probe:
      failureThreshold: 10 #
      httpGet:
        host: http://172.16.56.5
        path: /
        port: 80 #
        scheme: HTTP #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3    
