apiVersion: gslb.snappcloud.io/v1alpha1
kind: Gslb
metadata:
  name: gslb-simplest
  namespace: your-namespace
spec:
  serviceName: sth # URL would be `sth.app.internal.ha.snappcloud.io`
  backends:
  - name: inter-dc-teh-1
    host: sth.apps.inter-dc.teh-1.snappcloud.io
    probe:
      httpGet: {}
  - name: private-teh-2
    host: sth.apps.private.teh-1.snappcloud.io
    probe:
      httpGet: {}
  - name: svc-lb-teh-1
    host: "172.21.56.15"
    probe:
      httpGet: {}
---
apiVersion: gslb.snappcloud.io/v1alpha1
kind: Gslb
metadata:
  name: gslb-sample
  namespace: abar-internal
spec:
  # driverName:        # learn.internal.ha.snppacloud.io # learn.public.
  serviceName: learn
  # strategy: roundrobin, failover
  backends:
  - name: private-teh-1
    host: spcld-health2-be.apps.private.teh-1.snappcloud.io
    weight: "1" # TODO: implement logic
    probe:
      httpGet:
        host: "spcld-health2-be.apps.private.teh-1.snappcloud.io" # (optional) default to .spec.backends[].host
        path: / # (optional) default to "/"
        port: 80 # (optional) default based on scheme: 80 for http, 443 for https
        scheme: http # (optional) valid values: ["http", "http", "httpS", "https"], default to http
      periodSeconds: 5
      timeoutSeconds: 3
      initialDelaySeconds: 3 # TODO: implement logic: start critical?
      failureThreshold: 3 # TODO
      successThreshold: 1 # TODO
      # clusterRef: cluster-okd4-teh-1 // another CRD for external cluster


  - name: private-teh-2
    host: spcld-health2-be.apps.private.teh-2.snappcloud.io
    weight: "1"
    probe:
      httpGet: {}
  - name: svc-lb-teh-1
    host: "172.21.56.15"
    weight: "1"
    probe:
      failureThreshold: 3
      httpGet:
        host: "172.21.56.15"
        path: /
        port: 80 #
        scheme: http #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3
  - name: svc-lb-teh-2
    host: "172.16.56.5"
    weight: "1"
    probe:
      failureThreshold: 10 #
      httpGet:
        host: "172.16.56.5"
        path: /
        port: 80 #
        scheme: http #
      initialDelaySeconds: 3 #
      periodSeconds: 5
      successThreshold: 1 #
      timeoutSeconds: 3
